### ISSUE TITLE
Love it, but it isn't working anymore

### ISSUE THREAD

**Issue by lolloewe999** [IncredibleHacker/Fl00d-Attacker#1]
Everything worked fine first time (big respect for the layout and all that stuff), but now it can't find the flood.py file, which is in the exact same folder as the floodattack.sh file. I changed nothing, so, why did it work for the first time? Greetz

**Comment by lolloewe999** [comment]
Ahh yeah, I'm using Termux btw

**Comment by IncredibleHacker** [comment]
Thanks for contacting us 😇 if your flood-attack file not working, then
uninstall the flood-attack file And reinstall or again clone the file.

Uninstall command:- rm -rf Fl00d-Attacker
Reinstall command:- git clone
https://github.com/IncredibleHacker/Fl00d-Attacker

And I hope you star this repo And follow on GitHub And join our Whatsapp
group.

Thanks 😊
